import type { Metadata } from "next";
import { Sora, Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import Providers from "./providers";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { Toaster } from "@/components/ui/sonner";
import PageWatcher from "@/lib/misc/page-watcher";
import { LoginRedirect } from "@/lib/misc/login-redirect";
import PdfWatcher from "@/lib/misc/pdf-watcher";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/selfMade/sidebar";

const inter = Inter({
  subsets: ["latin"],
});

const sora = Sora({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <meta charSet="UTF-8"></meta>
      <body className={` ${inter.className}  antialiased  `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="min-h-screen pt-[12vh] w-full   ">
            <header>
              <Header />
            </header>
            <section className="md:min-h-[90vh] overflow-y-hidden">
              <Providers>
                <PageWatcher />
                <PdfWatcher />
                <LoginRedirect />
                {children}
              </Providers>
            </section>
            <footer>
              <Footer />
            </footer>
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
